name : 02 - workflows-events
on : push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              # ${{github.event_name}} is a contests used in Github Action , we will see later
              run: echo " I've been triggered by a{n} ${{github.event_name}}."
            
# So when you push code to GitHub:

# git push
#    ↓
# GitHub receives push
#    ↓
# push event happens
#    ↓
# GitHub Actions starts workflow

# GitHub knows:

# event_name = push

# Therefore:

# ${{ github.event_name }}

# becomes:

# push