name: Pull Request Workflow

# pull_request : when a branch gives pull request to the main.
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger
        run: echo "Workflow triggered by ${{ github.event_name }}"

      - name: Test
        run: echo "Running tests..."