name : 04 - GitHub Runner Workflow
on : 
    push:

jobs:
    ubuntu-runner:
        runs-on : ubuntu-latest
        steps:
            - name: Show OS
              # $RUNNER_OS is one of the traditional shell commands for Linux OS
              run: |
                echo "Running GitHub Runner..."
                echo "Machine : $RUNNER_OS"
    windows-runner:
        runs-on : windows-latest
        steps:
         - name: Show OS
           # If we want to use $RUNNER_OS in windows , we should use "shell : bash"
           shell: bash
           run: |
                echo "Running GitHub Runner..."
                echo "Machine : $RUNNER_OS"
