name: 05-2-Event Filters and Activity Types

on:
   pull_request:
   # whenever the pull request gets closed
     types:
       - closed
     branches :
       - main

jobs:
   echo:
      runs-on: ubuntu-latest
      steps:
        - run : echo "Running whenever s PR is closed "